spring:
  application:
    name: suongmai

  datasource:
    # URL kết nối tới PostgreSQL container đang mở tại localhost:5433
    url: jdbc:postgresql://localhost:5433/suongmai_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    # hibernate ddl-auto:
    # - "none": Không tự động tạo hay sửa bảng
    # - "update": Tự động cập nhật bảng theo các @Entity class mà không xóa dữ liệu cũ
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080